// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBposSkhdeVOx_uwirDUlbtvVO--rcOw_0',
    appId: '1:657316449788:android:60a294c16ddfa87a633679',
    messagingSenderId: '657316449788',
    projectId: 'mg-game-0001',
    storageBucket: 'mg-game-0001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0rwNQlONLuQUotP1BpzQDdq7L5G4I0cM',
    appId: '1:657316449788:ios:ff9be6997403b344633679',
    messagingSenderId: '657316449788',
    projectId: 'mg-game-0001',
    storageBucket: 'mg-game-0001.firebasestorage.app',
    iosBundleId: 'com.example.towerDefense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0rwNQlONLuQUotP1BpzQDdq7L5G4I0cM',
    appId: '1:657316449788:ios:ff9be6997403b344633679',
    messagingSenderId: '657316449788',
    projectId: 'mg-game-0001',
    storageBucket: 'mg-game-0001.firebasestorage.app',
    iosBundleId: 'com.example.towerDefense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIwc9frhOF2IDmyfsUjQlUWMQDvO7XtX0',
    appId: '1:657316449788:web:dfd98636c0393f0c633679',
    messagingSenderId: '657316449788',
    projectId: 'mg-game-0001',
    authDomain: 'mg-game-0001.firebaseapp.com',
    storageBucket: 'mg-game-0001.firebasestorage.app',
    measurementId: 'G-MMQV8FGXZQ',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIwc9frhOF2IDmyfsUjQlUWMQDvO7XtX0',
    appId: '1:657316449788:web:60b31781897ef649633679',
    messagingSenderId: '657316449788',
    projectId: 'mg-game-0001',
    authDomain: 'mg-game-0001.firebaseapp.com',
    storageBucket: 'mg-game-0001.firebasestorage.app',
    measurementId: 'G-N2LVSPYLE5',
  );
}
